# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'INTERNZ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for INTERNZ
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'CHIPageControl', '~> 0.1.3'


end
